name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   

    steps:
      - name: Ckeckout
        uses: action/ckeckout@v3

      - name: Step Node.js
        uses: action/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci 

      - name: Build Storybook
        run: npm build-storybook  

      - name: Deploy Storybook
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
